name: 'Generate Offline Dependecies'
description: 'Generate Offline Dependecies'
inputs:
  generator:
    description: 'CMake generator to use'
    required: true
  build_type:
    description: 'Build type. Valid values are: Debug, Release, RelWithDebInfo, MinSizeRel'
    required: false
    default: RelWithDebInfo
  cmake_options:
    description: 'Additional options for the CMake'
    required: false
  additional_python_packages:
    description: "Additional Python packages to cache"
    required: false
runs:
  using: 'node16'
  main: '../dist/generate_offline_dependencies/index.js'
