name: 'Setup Dependencies'
description: 'Prepare the build environment for Audacity'
inputs:
  force_gcc11:
    description: "Force GCC 11 on Linux"
    required: false
    default: false
runs:
  using: "composite"
  steps:
  - name: Switch to GCC 11 on linux
    shell: bash
    if: ${{ inputs.force_gcc11 == 'true' && runner.os== 'Linux' }}
    run: |
        sudo apt update
        sudo apt install gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
        sudo update-alternatives --set gcc /usr/bin/gcc-11
  - name: Install required libraries
    shell: bash
    if: ${{ runner.os== 'Linux' }}
    run: |
        apt_packages=(
            # For self hosted runners
            build-essential
            cmake
            # For Audacity
            libasound2-dev
            libgtk2.0-dev
            libjack-jackd2-dev
            gettext
            python3-pip
            libgl1-mesa-dev
            uuid-dev
            # For Qt building
            libx11-dev
            libx11-xcb-dev
            libfontenc-dev
            libice-dev
            libsm-dev
            libxau-dev
            libxaw7-dev
            libxcomposite-dev
            libxcursor-dev
            libxdamage-dev
            libxdmcp-dev
            libxext-dev
            libxfixes-dev
            libxi-dev
            libxinerama-dev
            libxkbfile-dev
            libxmu-dev
            libxmuu-dev
            libxpm-dev
            libxrandr-dev
            libxrender-dev
            libxres-dev
            libxss-dev
            libxt-dev
            libxtst-dev
            libxv-dev
            libxvmc-dev
            libxxf86vm-dev
            libxcb-render0-dev
            libxcb-render-util0-dev
            libxcb-xkb-dev
            libxcb-icccm4-dev
            libxcb-image0-dev
            libxcb-keysyms1-dev
            libxcb-randr0-dev
            libxcb-shape0-dev
            libxcb-sync-dev
            libxcb-xfixes0-dev
            libxcb-xinerama0-dev
            libxcb-dri3-dev
            libxcb-util0-dev
            libxcb-cursor-dev
            # xkeyboard-config
            xkb-data
            # It appears that CCI M4 package does not work correctly
            m4
        )

        sudo apt-get update
        sudo apt-get install -y --no-install-recommends "${apt_packages[@]}"
        sudo apt-get remove -y ccache
  - name: Generate requirements
    shell: bash
    run: |
        echo "conan==2.4.0" > requirements.txt
  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.10'
      cache: 'pip'
  - uses: BSFishy/pip-action@v1
    with:
      requirements: requirements.txt
