name: 'Setup Dependencies'
description: 'Prepare the build environment for Audacity'
inputs:
  force_gcc11:
    description: "Force GCC 11 on Linux"
    required: false
    default: false
runs:
  using: "composite"
  steps:
  - name: Prepare the build environment
    shell: bash
    if: ${{ runner.os== 'Linux' }}
    run: |
        echo "Preparing the build environment"
        ${GITHUB_ACTION_PATH}/setup_linux.sh "${{ inputs.force_gcc11 }}"
  - name: Setup cmake
    uses: jwlawson/actions-setup-cmake@v2
    with:
      cmake-version: '3.24.x'
  - name: Generate requirements
    shell: bash
    run: |
        echo "conan==2.4.0" > requirements.txt
  - name: Setup Python
    uses: actions/setup-python@v5
    if: ${{ runner.os != 'Linux' }}
    with:
      python-version: '3.11'
      cache: 'pip'
  - uses: BSFishy/pip-action@v1
    with:
      requirements: requirements.txt
