name: Build Dependencies

on:
  workflow_dispatch:
jobs:
  build:
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_HOST: ${{ secrets.SENTRY_HOST }}
      SENTRY_ORG_SLUG: ${{ secrets.SENTRY_ORG_SLUG }}
      SENTRY_PROJECT_SLUG: ${{ secrets.SENTRY_PROJECT_SLUG }}
      ARTIFACTORY_SYMBOLS_URL: ${{ secrets.ARTIFACTORY_SYMBOLS_URL }}
      ARTIFACTORY_SYMBOLS_KEY: ${{ secrets.ARTIFACTORY_SYMBOLS_KEY }}
      CONAN_BINARIES_REMOTE: ${{ secrets.CONAN_BINARIES_REMOTE }}
      CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
      CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Ubuntu_18.04
          os: ubuntu-18.04
          arch: x64
          generator: Unix Makefiles
          force_gcc11: false
          build_type: RelWithDebInfo
        - name: Ubuntu_18.04_Debug
          os: ubuntu-18.04
          arch: x64
          generator: Unix Makefiles
          force_gcc11: false
          build_type: Debug

        - name: Ubuntu_20.04
          os: ubuntu-20.04
          arch: x64
          generator: Unix Makefiles
          force_gcc11: false
          build_type: RelWithDebInfo
        - name: Ubuntu_20.04+Debug
          os: ubuntu-20.04
          arch: x64
          generator: Unix Makefiles
          force_gcc11: false
          build_type: Debug

        - name: Ubuntu_20.04_GCC11
          os: ubuntu-20.04
          arch: x64
          generator: Unix Makefiles
          force_gcc11: true
          build_type: RelWithDebInfo
        - name: Ubuntu_20.04_GCC11_Debug
          os: ubuntu-20.04
          arch: x64
          generator: Unix Makefiles
          force_gcc11: true
          build_type: Debug

        - name: macOS_Intel
          os: macos-11
          arch: x64
          generator: Xcode
          force_gcc11: false
          build_type: RelWithDebInfo

        - name: macOS_AppleSilicon
          os: macos-11
          arch: arm64
          generator: Xcode
          force_gcc11: false
          build_type: RelWithDebInfo

        - name: Windows_32bit_2019
          os: windows-2019
          arch: x32
          generator: Visual Studio 16 2019
          force_gcc11: false
          build_type: RelWithDebInfo

        - name: Windows_64bit_2019
          os: windows-2019
          arch: x64
          generator: Visual Studio 16 2019
          force_gcc11: false
          build_type: RelWithDebInfo

        - name: Windows_32bit_2022
          os: windows-2022
          arch: x32
          generator: Visual Studio 17 2022
          force_gcc11: false
          build_type: RelWithDebInfo

        - name: Windows_64bit_2022
          os: windows-2022
          arch: x64
          generator: Visual Studio 17 2022
          force_gcc11: false
          build_type: RelWithDebInfo
    steps:
    - name: Checkout Audacity
      uses: actions/checkout@v2
      with:
        repository: crsib/audacity
        ref: 2223_apple_silicon
    - name: Setup dependencies
      uses: audacity/audacity-actions/dependencies@v1
      with:
        force_gcc11: ${{ matrix.config.force_gcc11 }}
    - name: Configure
      uses: audacity/audacity-actions/configure@v1
      with:
        generator: ${{ matrix.config.generator }}
        configuration_types: Debug;Release;RelWithDebInfo;MinSizeRel
        build_type: ${{ matrix.config.build_type }}
