name: Package

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: macos-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        architecture: x64
    - uses: actions/checkout@v4
      with:
        ref: conan2
    - run: npm install
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
